"use client";
import QuizComponent from "@/components/QuizComponent";

const questions = [
  { id: 1, question: "What is Docker?", options: ["A virtual machine", "A containerization platform", "A programming language", "A database"], correctAnswer: 1 },
  { id: 2, question: "Which command is used to build a Docker image from a Dockerfile?", options: ["docker run", "docker build", "docker create", "docker commit"], correctAnswer: 1 },
  { id: 3, question: "What is the default location for Docker images on a local machine?", options: ["/var/lib/docker", "/etc/docker", "/usr/local/docker", "/opt/docker"], correctAnswer: 0 },
  { id: 4, question: "Which command lists all running containers?", options: ["docker ps", "docker ps -a", "docker list", "docker container ls -a"], correctAnswer: 0 },
  { id: 5, question: "How do you stop a running Docker container?", options: ["docker stop <container>", "docker kill <container>", "docker rm <container>", "docker pause <container>"], correctAnswer: 0 },
  { id: 6, question: "What is the purpose of a Dockerfile?", options: ["To define environment variables", "To automate Docker image creation", "To manage Docker networks", "To store container logs"], correctAnswer: 1 },
  { id: 7, question: "Which command is used to download a Docker image from a registry?", options: ["docker pull", "docker push", "docker load", "docker import"], correctAnswer: 0 },
  { id: 8, question: "What does the `-d` flag do in `docker run`?", options: ["Run container in detached mode", "Delete container after exit", "Enable debugging", "Define domain name"], correctAnswer: 0 },
  { id: 9, question: "Which command removes a stopped container?", options: ["docker rm", "docker rmi", "docker container prune", "Both A and C"], correctAnswer: 3 },
  { id: 10, question: "What is a Docker image?", options: ["A running container", "A lightweight, standalone, executable package", "A virtual machine snapshot", "A Docker Compose file"], correctAnswer: 1 },
  { id: 11, question: "How can you execute a command inside a running container?", options: ["docker exec", "docker run", "docker attach", "docker shell"], correctAnswer: 0 },
  { id: 12, question: "What is the default registry for Docker images?", options: ["Docker Hub", "Google Container Registry", "Amazon ECR", "Azure Container Registry"], correctAnswer: 0 },
  { id: 13, question: "Which command shows the logs of a container?", options: ["docker logs", "docker events", "docker inspect", "docker stats"], correctAnswer: 0 },
  { id: 14, question: "What is Docker Compose used for?", options: ["Orchestrating containers across multiple hosts", "Defining and running multi-container Docker applications", "Building Docker images", "Managing Docker networks"], correctAnswer: 1 },
  { id: 15, question: "Which flag maps a host port to a container port?", options: ["-p", "-P", "--port", "-e"], correctAnswer: 0 },
  { id: 16, question: "What is the difference between an image and a container?", options: ["An image is a template, a container is a running instance", "They are the same thing", "A container is read-only, an image is writable", "Images are stored in registries, containers are local"], correctAnswer: 0 },
  { id: 17, question: "How do you remove all unused containers, networks, and images?", options: ["docker system prune", "docker clean", "docker garbage collect", "docker purge"], correctAnswer: 0 },
  { id: 18, question: "Which command displays resource usage statistics of containers?", options: ["docker stats", "docker top", "docker info", "docker system df"], correctAnswer: 0 },
  { id: 19, question: "What is a Docker volume?", options: ["A way to persist data generated by containers", "A type of Docker image", "A network driver", "A logging driver"], correctAnswer: 0 },
  { id: 20, question: "Which instruction in a Dockerfile sets the default command to run when the container starts?", options: ["CMD", "RUN", "ENTRYPOINT", "START"], correctAnswer: 0 }
];

export default function DockerTest() {
  return (
    <QuizComponent
      title="Docker Quiz"
      description="20 questions – 60 seconds each"
      questions={questions}
    />
  );
}